#!/usr/bin/env bash                                                            
# set up Nginx to run as nginx user                                                          
#pkill apache2
#sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/d\
#efault
#chown nginx:nginx /etc/nginx/nginx.conf
#chmod 700 /etc/nginx/nginx.conf
#service nginx reload
#service nginx restart
sed -i 's/user  nginx;/user  nginx;\n/g' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 0.0.0.0:8080;/g' /etc/nginx/conf.d/default.conf
nginx -s reload
