#!/usr/bin/env bash
# Run nginx as nginx
#pkill apache2
#sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
#chown nginx:nginx /etc/nginx/nginx.conf
#chown 755 /etc/nginx/nginx.conf
#sudo -u nginx service nginx restart
sed -i 's/user  nginx;/user  nginx;\n/g' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 0.0.0.0:8080;/g' /etc/nginx/conf.d/default.conf
nginx -s reload
